@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package plus.dragons.createclassicblazeenchanter.config;

import javax.annotation.ParametersAreNonnullByDefault;
import net.minecraft.MethodsReturnNonnullByDefault;
